### ISSUE TITLE
Doesn't work on Xcode 13 Beta 4

### ISSUE THREAD

**Issue by marcusziade** [NordicSemiconductor/IOS-CoreBluetooth-Mock#49] opened 2021-07-28 07:54 UTC
Please compile this with Swift 5.5

**Comment by philips77** [comment] 2021-07-28 08:52
Is it the same as #41?

**Comment by marcusziade** [comment] 2021-07-28 13:10
IIRC, yes.

**Comment by philips77** [comment] 2021-07-29 09:59
Duplicate of #41

**Closed by philips77** 2021-07-29 09:59 UTC
